# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Computer Graphics 
email: jinified@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Keep track of materials and concepts of Computer Graphics and Visual Design
baseurl: "/opengl_experiment" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: jinified
github_username:  jinified

# Build settings
markdown: kramdown
